# TP-2_Cálculo-Númerico

### Implementação da função 7, Sistemas Lineares: Gauss-Siedel

In [23]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sym
import math
import seaborn as sns
import sys
from copy import copy

In [24]:
def gauss_seidel(A, b, x0, tol=1e-6, max_iter=1000):
    n = len(b)
    x = np.copy(x0)
    
    for _ in range(max_iter):
        x_old = np.copy(x)
        for i in range(n):
            sum1 = sum(A[i, j] * x[j] for j in range(n) if j != i)
            x[i] = (b[i] - sum1) / A[i, i]
        
        error = np.linalg.norm(x - x_old, ord=np.inf)
        
        if error < tol:
            return x
        
    raise ValueError("A solução não converge dentro do número máximo de iterações.")

A = np.array([[4, 1, 2], [3, 5, 1], [1, 1, 3]], dtype=float)
b = np.array([4, 7, 3], dtype=float)
x0 = np.zeros_like(b)

solucao = gauss_seidel(A, b, x0)
print(f"A solução aproximada é: x = {solucao}")

A solução aproximada é: x = [0.50000005 0.99999998 0.49999999]


### Implementação da função 6, Sistemas Lineares: Gauss-Jacobi


In [25]:
def gauss_jacobi(A, b, x0, tol=1e-6, max_iter=1000):
    n = len(b)
    x = np.copy(x0)
    
    for iter_count in range(max_iter):
        x_new = np.copy(x)
        
        for i in range(n):
            sum1 = sum(A[i, j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - sum1) / A[i, i]
        
        error = np.linalg.norm(x_new - x, ord=np.inf)

        if error < tol:
            return x_new
        
        x = x_new
    
    raise ValueError("A solução não converge dentro do número máximo de iterações.")

A = np.array([[4, 1, 2], [3, 5, 1], [1, 1, 3]], dtype=float)
b = np.array([4, 7, 3], dtype=float)
x0 = np.zeros_like(b)

solucao = gauss_jacobi(A, b, x0)
print(f"A solução aproximada é: x = {solucao}")

A solução aproximada é: x = [0.50000036 1.00000038 0.50000034]


### Implementação da função 3, diferenças divididas:

In [26]:
def proterm(i, value, x): 
    pro = 1
    for j in range(i): 
        pro = pro * (value - x[j])
    return pro

def dividedDiffTable(x, y, n):
    for i in range(1, n): 
        for j in range(n - i): 
            y[j][i] = (y[j][i - 1] - y[j + 1][i - 1]) / (x[j] - x[i + j])
    return y
  
def applyFormula(value, x, y, n): 
    sum = y[0][0]
    for i in range(1, n):
        sum = sum + (proterm(i, value, x) * y[0][i])
    return sum
  
def printDiffTable(y, n): 
    for i in range(n): 
        for j in range(n - i): 
            print(round(y[i][j], 4), "\t", end=" ")
        print("")

def divided_difference(n, x_list, y_list, value):
    y = [[0 for i in range(n)] for j in range(n)]
    for i in range(n):
        y[i][0] = y_list[i]

    y = dividedDiffTable(x_list, y, n)
    printDiffTable(y, n)
    
    result = round(applyFormula(value, x_list, y, n), 2)
    return result

# Example usage for Newton Divided Differences

n = 3
x_list = [11, 12, 13] 
y_list = [1400, 2500, 3250]
value = 10

resultado_dividido = divided_difference(n, x_list, y_list, value)
print(f"O valor interpolado em {value} é: {resultado_dividido}")


1400 	 1100.0 	 -175.0 	 
2500 	 750.0 	 
3250 	 
O valor interpolado em 10 é: -50.0


### Implementação da função 4, Sistemas Lineares: Gauss

In [27]:
def metodo_gauss(A, B):
    # Combina a matriz A e o vetor B em uma única matriz aumentada [A|B]
    AB = np.hstack([A, B.reshape(-1, 1)])
    n = len(B)
    
    # Aplicando eliminação gaussiana
    for i in range(n):
        # Pivotamento parcial
        max_row = np.argmax(np.abs(AB[i:, i])) + i
        AB[[i, max_row]] = AB[[max_row, i]]
        
        # Eliminação
        for j in range(i + 1, n):
            factor = AB[j, i] / AB[i, i]
            AB[j, i:] -= factor * AB[i, i:]
    
    # Substituição para encontrar as soluções
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (AB[i, -1] - np.dot(AB[i, i + 1:n], x[i + 1:])) / AB[i, i]
    
    return AB, x

# Exemplo de uso:
# A = np.array([[1, -2, 1], [2, -3, 1], [1, 4, 2]], dtype=float)
# B = np.array([-1, -3, 7], dtype=float)

# A = np.array([[4, 1, 2], [3, 5, 1], [1, 1, 3]], dtype=float)
# B = np.array([4, 7, 3], dtype=float)

A = np.array([[0, 1, -2], [2, -2, 3], [1, 3, 1]], dtype=float)
B = np.array([7, -10, 8], dtype=float)

AB, x = metodo_gauss(A, B)
print("Matriz A:\n", A)
print("Matriz B:\n", B)
print("\nMatriz aumentada [A|B] após eliminação gaussiana:")
print(AB)
print("\nSolução do sistema, vetor x:")
print(x)


Matriz A:
 [[ 0.  1. -2.]
 [ 2. -2.  3.]
 [ 1.  3.  1.]]
Matriz B:
 [  7. -10.   8.]

Matriz aumentada [A|B] após eliminação gaussiana:
[[  2.     -2.      3.    -10.   ]
 [  0.      4.     -0.5    13.   ]
 [  0.      0.     -1.875   3.75 ]]

Solução do sistema, vetor x:
[ 1.  3. -2.]


### Implementação da função 5, Sistemas Lineares: Decomposição LU: